{% set name = "tty-screen" %}
{% set version = "0.7.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: ce7f1f7cdedee3aac88c82e4aa6b8e8bd23feb673d14d4eb7896463ea2c88fcb

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: 'Terminal screen size detection which works on Linux, OS X and Windows/Cygwin platforms and supports MRI, JRuby and Rubinius interpreters.'
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/piotrmurach/tty-screen

extra:
  recipe-maintainers:
    - sodre
    - rluria14
    - oblute
    - benhuff
