{% set name = "tty-screen" %}
{% set version = "0.8.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: c090652115beae764336c28802d633f204fb84da93c6a968aa5d8e319e819b50

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >=2.5
  run:
    - ruby >=2.5

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: 'Terminal screen size detection which works on Linux, OS X and Windows/Cygwin platforms and supports MRI, JRuby and Rubinius interpreters.'
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/piotrmurach/tty-screen

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - rluria14
    - oblute
    - benhuff
