travis:
  secure:
    BINSTAR_TOKEN: h7tW+n+aMzmboZWq43BfNwZE3fbYZ/sFtmwHzOK68tgDyfEWK/voGS7rM9tZWnCsJu6dn7qz/DDOPi7AN1H1BznY/DqLOBM0DTcDQ5HiyP5yAq4SJyRN6/qLpZfIp+6qKHe2tGj7YQj4l5MPWbq6S41aLXAS3Ug6RAqVFU6pmqEb3LQdEyDshMkaw5pV+ezhDGNooqaJOK4KVfVL6kAPUd+lfVqeWOugJSJU8tGru1fEHV2lTRpPRWr8j+NfeR6lEumoREcp6i1hlHS9iMhBALpEXbt+XH1e6QSEOKDJLz0wnlpeHqrErYPsP/WO799o8PKowiCdg0oWTj9+hhM/dF2eVE4k1ZhMK7s9zgq+nn5Qc/y/tewGTHQTpPU2j/XxpYYtgHLo/7wskER/ewdfVpQ5qjE+ak/zVTq4reNKJzVWtHyQyjNaDM76P/W+oiMxozEWLhAnKCOyFg0ErWYTG0Rckh5p2XNNmfu9ANnR9pp5SXQp3BuIn8c/dtBrzym79dr5LSQtZrPEomw/oMFjqr/JCgWedx2TeeoLGXSQ+yYhX3a/MJN/YM636zk8NM1s5JJX/pBGPAgaIm/7w72Q3o8xlA3SLacEZ+40KvCmrXx2B9A3ONFKx38QMM7mMyt887y16Yz96ne15QhYVzVK49SmTll5htScrwaAB+CpWYc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
